### ISSUE TITLE
Can you elaborate on what blocking is?

### ISSUE THREAD

**Issue by lipid** [88/mojang-api-docs#3]
I was reading your docs and I saw this:
```
A quick word on blocking
Blocking can happen either one of two ways - a username sniper has blocked the name for 24 hours on an empty Mojang account, or the username has been blocked by Mojang's inappropriate name filter for whatever reason. The reasons names are blocked aren't public, but this is the best way to check if a name is blocked.
```

How does a username sniper block the name for 24 hours? Can this keep happening?

**Comment by wh-at** [comment]
Hi, apologies for the late response. I wasn't alerted of this issue for some reason...

The API route to block usernames no longer exists and was removed on December 1st, 2020.

There is no route nor capability to block a username anymore via Mojang's public-facing API. As far as I'm aware, usernames can still be blocked by Mojang themselves if the names are offensive.

**Comment by lipid** [comment]
no issue I think my account got flagged. How did this route work prior to it being removed? Anyone could just block a username via the route? Why would snipers do this (and why was it publicly accessible) if you know?

**Comment by wh-at** [comment]
Prior to it being removed, the route worked like so: the user sends a PUT request to https://api.mojang.com/user/profile/agent/minecraft/name/IGN_HERE, authorized correctly with an empty Mojang account (no Minecraft profile can exist on this account). After this, the name is blocked for 24 hours if status code returned is 204, otherwise there was an issue blocking.

Snipers would do this for a few reasons.

First off, this route was the only way to "giftcode snipe" a name back then. The name would be blocked and then the sniper could manually redeem the giftcode on minecraft.net later, and the name would be put onto the giftcode, thus creating a Minecraft profile, without unblocking it. If you redeemed the code on account.mojang.com, the name would be unblocked and put on the giftcode. 

Next, snipers used blocking also because of the fact that blocking had priority over namechanging. Name change requests were not prioritized as they are now, before the API changes of 1st December 2020, the blocking endpoint had higher chance of success.

In addition, snipers chose to use blocking due to how actually claiming the name worked. Blocking a name meant that the only thing the sniper needed to do was actually block it, not claim it on the user's provided account within such a short timeframe. They could leave the name blocked for hours until importing an unmigrated account to claim the name or redeeming a giftcode to claim the name, both of which would happen on the empty Mojang account that blocked the name. This basically means that both importing an unmigrated account + changing the name and redeeming a giftcode to claim the name on a fresh profile did NOT need the name to be unblocked meaning there was zero chance of the name being stolen by a turbo once it was blocked. Migrated accounts needed the name to be unblocked first, then within 3 seconds or less, the name would be claimed on the customer's migrated account. This did have a chance of turboing (someone else getting the block on the name as it was unblocked for a few seconds) but it wasn't as bad as that happening for the most common ways of putting the name onto a profile (unmigrated accounts or giftcode).

Finally, snipers also used blocking because it was very inexpensive for them. As opposed to getting thousands of MFA accounts, snipers could instead create thousands, maybe tens of thousands, of empty Mojang accounts for free, and use proxies on each one to send a mass amount of block requests before and after the drop of the name in order to have a better chance at claiming it. 

Why was it public? Good question. Essentially, the normal user signup process on an empty Mojang account when redeeming a giftcode involved this API route. You redeemed the giftcode, blocked the name, then hit another route to create the profile with those two things already on the account.

I hope this clarified things. Sorry for the wall of text.

**Comment by lipid** [comment]
I see, thanks for the detailed explanation!
